### ISSUE TITLE
DefinitelyTyped linting error

### ISSUE THREAD

**Issue by namoscato** [Bolisov/google-api-typings-generator#13]
[DefinitelyTyped linting](https://github.com/DefinitelyTyped/DefinitelyTyped#verifying) is failing ([`no-unnecessary-qualifier`](https://palantir.github.io/tslint/rules/no-unnecessary-qualifier/)) due to resource name constant type qualifications, i.e.

```
[~/dev/git/google-api-typings-generator]$ npm start -- --out ~/dev/git/DefinitelyTyped/types --url "https://sheets.googleapis.com/\\\$discovery/rest?version=v4"
```

```
[~/dev/git/DefinitelyType]$ npm run lint gapi.client.sheets/v4

> definitely-typed@0.0.3 lint /Users/namoscato/dev/git/DefinitelyTyped
> dtslint types "gapi.client.sheets/v4"

Error: /Users/namoscato/dev/git/DefinitelyTyped/types/gapi.client.sheets/v4/index.d.ts:3854:29
ERROR: 3854:29  no-unnecessary-qualifier  Qualifier is unnecessary since 'sheets' is in scope.

    at /Users/namoscato/dev/git/DefinitelyTyped/node_modules/dtslint/bin/index.js:193:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/namoscato/dev/git/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

**Comment by namoscato** [comment]
Closing in favor of more active fork: [Maxim-Mazurok/google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator).
